# Generated by Django 4.0.4 on 2022-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('native', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('size', models.CharField(max_length=100)),
                ('danger', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
