# Generated by Django 4.0.4 on 2022-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beast',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
