# Generated by Django 4.0.4 on 2022-06-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_beast_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beast',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance', models.CharField(choices=[('S', 'Short Walk'), ('L', 'Long Walk'), ('F', 'Fly'), ('N', 'Swim')], default='S', max_length=1)),
                ('beast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.beast')),
            ],
        ),
    ]
