# Generated by Django 4.0.4 on 2022-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_beast_options_walk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('environment', models.CharField(choices=[('C', 'Cities'), ('F', 'Forests'), ('M', 'Mountains'), ('O', 'Oceans'), ('R', 'Rivers'), ('U', 'Underground')], default='C', max_length=1)),
                ('image', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='walk',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='walk',
            name='date',
            field=models.DateField(verbose_name='Exercise Date'),
        ),
        migrations.AddField(
            model_name='beast',
            name='locations',
            field=models.ManyToManyField(to='main_app.location'),
        ),
    ]
