# Generated by Django 4.0.4 on 2022-06-24 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_location_alter_walk_options_alter_walk_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beast',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='environment',
            field=models.CharField(choices=[('C', 'Cities'), ('F', 'Forests'), ('L', 'Lakes'), ('M', 'Mountains'), ('O', 'Oceans'), ('R', 'Rivers'), ('U', 'Underground')], default='C', max_length=1),
        ),
    ]
